import { config, isSimulated } from '../telemetry/config';
import { JOINT_LIMITS_DEG, JOINT_NAMES } from '../telemetry/fr5Model';
import type { ContactSnapshot } from '../telemetry/contactState';
import type { RobotTelemetry } from '../telemetry/types';
import { SAFETY_STATE_LABEL } from '../store/selectors';
import styles from './SafetyPanel.module.css';

interface Props {
  telemetry: RobotTelemetry;
  contact: ContactSnapshot;
  available: boolean;
}

/**
 * Safety view.
 *
 * Two halves. On the left the configured limits, so the operator can see what
 * this console is comparing against without opening a YAML file. On the right
 * the standing caveats — the things that make the numbers less trustworthy
 * than they look, each with the reason stated rather than a warning glyph.
 */
export function SafetyPanel({ telemetry, contact, available }: Props) {
  const safety = telemetry.safetyState;
  const alarm = safety === 'protective_stop' || safety === 'emergency_stop';

  return (
    <section className="plate">
      <div className="plate__head">
        <span className="plate__title">Safety limits and standing caveats</span>
        <span className="plate__aside">source: fr5_control/config/probe.yaml</span>
      </div>

      <div className={`plate__body ${styles.body}`}>
        <div className={styles.col}>
          <h3 className={styles.subhead}>Configured limits</h3>
          <Row label="Contact enter" value={`${config.contactEnterN.toFixed(1)} N`} note="safety.max_contact_force_n" />
          <Row label="Contact release" value={`${config.contactReleaseN.toFixed(1)} N`} note="watchdog.retreat_until_force_n" />
          <Row label="Warning" value={`${config.warnForceN.toFixed(1)} N`} note="safety.warn_contact_force_n" />
          <Row label="Force sign" value={`Fn = ${config.normalForceSign > 0 ? '+' : '−'}Fz`} note="ft_sensor.normal_force_sign" />
          <Row label="Confirm windows" value="5 ms enter · 50 ms release" note="contact_state.py" />

          <h3 className={styles.subhead}>Joint limits · deg</h3>
          <table className={styles.jointTable}>
            <tbody>
              {JOINT_NAMES.map((name, i) => (
                <tr key={name}>
                  <th scope="row">{name}</th>
                  <td className="num">{JOINT_LIMITS_DEG.lower[i].toFixed(0)}</td>
                  <td className={styles.dots}>…</td>
                  <td className="num">{JOINT_LIMITS_DEG.upper[i].toFixed(0)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className={styles.col}>
          <h3 className={styles.subhead}>Current declaration</h3>
          <div className={`field ${alarm ? 'field--alarm' : ''}`}>
            <span className="field__label">Controller safety state</span>
            <span className="field__value num">
              {available && safety ? SAFETY_STATE_LABEL[safety].toUpperCase() : 'UNKNOWN'}
            </span>
          </div>
          <div className="field">
            <span className="field__label">Stage classifier</span>
            <span className="field__value num">
              {contact.phase.toUpperCase()} · {Math.abs(contact.contactForceN).toFixed(2)} N
            </span>
          </div>
          <div className="field">
            <span className="field__label">Session recording</span>
            <span className="field__value num">NOT CONFIGURED</span>
          </div>
          <div className="field">
            <span className="field__label">Ultrasound image source</span>
            <span className="field__value num">NOT CONNECTED</span>
          </div>

          <h3 className={styles.subhead}>Standing caveats</h3>
          <ul className={styles.caveats}>
            {isSimulated ? (
              <Caveat title="Simulated source">
                No robot or sensor is connected. Every value on this console is
                generated by the built-in simulator.
              </Caveat>
            ) : null}
            <Caveat title="Probe weight not compensated">
              payload.mass_kg is unidentified, so the normal force carries a
              pose-dependent gravity term of roughly 1.5 N. Every force threshold
              inherits that error.
            </Caveat>
            <Caveat title="Sensor axis assignment provisional">
              The PX6D manual §5.3 and §5.4 disagree, and normal_force_sign has not
              been verified against hardware.
            </Caveat>
            <Caveat title="Tool transform unmeasured">
              tool.j6_to_probe is still .nan, so the workspace view marks the J6
              flange rather than the probe contact point.
            </Caveat>
            <Caveat title="No force feedback loop">
              Phase 0 runs servo and differential IK only. Admittance control, the
              supervisor and the force barrier are not implemented — this console
              observes, it does not intervene.
            </Caveat>
          </ul>
        </div>
      </div>
    </section>
  );
}

function Row({ label, value, note }: { label: string; value: string; note: string }) {
  return (
    <div className={styles.limitRow}>
      <span className={styles.limitLabel}>{label}</span>
      <span className={`num ${styles.limitValue}`}>{value}</span>
      <span className={styles.limitNote}>{note}</span>
    </div>
  );
}

function Caveat({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <li>
      <span className={styles.caveatTitle}>{title}</span>
      <span className={styles.caveatText}>{children}</span>
    </li>
  );
}
